### ISSUE TITLE
feature/BotAss-Ticket3 - Validation Data

### ISSUE THREAD

**Issue by mardaxrakys** [Neoversity/PPF_BP_Personal_assistant#15]
Валідація введених даних

Додайте функції для перевірки правильності введених номерів телефонів та електронних адрес.

**Comment by bobantonbob** [comment]
def is_valid_phone(phone): я додав у файл utils.py 
для прикладу та перевірки  так само мож робити

**Comment by bobantonbob** [comment]
раджу додати також 
def is_valid_birthday(birthday):
щоб він не перевищував 100 років назад від поточного року. 
там декілька строк
