### ISSUE TITLE
feature/BotAss-Ticket4 - List Contacts

### ISSUE THREAD

**Issue by mardaxrakys** [Neoversity/PPF_BP_Personal_assistant#16]
Список контактів

Реалізуйте можливість виводу списку контактів та пошук контактів.

"all"
"phone"

**Comment by bobantonbob** [comment]
"all": self.show_all_contacts,  це список всіх контактів

"phone": self.phone_search, це пошук контакту по номеру, типа я мамятаю номер 3333 він видасть всіх у кого в телефоні є таке
