### ISSUE TITLE
feature/BotAss-Ticket5 - Birthdays

### ISSUE THREAD

**Issue by bobantonbob** [Neoversity/PPF_BP_Personal_assistant#19]
Дні народження

Додайте функціонал для виведення контактів, у яких день народження через задану кількість днів від поточної дати.

"add-birthday
"show-birthday"
"show_all_birthdays"
"birthdays"

**Comment by Vitalii1983-vr** [comment]
Додав функціонал для виведення контактів, у яких день народження через задану кількість днів від поточної дати.

**Comment by bobantonbob** [comment]
"add-birthday"  це додати або змінити день народження контакту

"show-birthday" це показати по id контакт ім'я та день народження

"show_all_birthdays" це показати всі контакти ім'я та день народження

**Comment by Vitalii1983-vr** [comment]
Добре. Хотів ще уточнити, по пункту 4 birthdays мого завдання, якщо 1-3 це:  
1. "add-birthday - додати або змінити день народження контакту
2. "show-birthday" - показати по id контакт ім'я та день народження
3. "show_all_birthdays" - показати всі контакти ім'я та день народження
то
4. "birthdays" - чи правильно я зрозумів, як в нас було по останньому домашньому завданню, повинен показувати контакти, у яких день народження наступає протягом найближчого тижня та виводити список контактів з відповідними днями народження?

**Comment by bobantonbob** [comment]
"birthdays" - Виведення списку контактів, у яких день народження через задану кількість днів від поточної дати

**Comment by Vitalii1983-vr** [comment]
Зрозуміло

**Comment by bobantonbob** [comment]
доречи ти кодиш  у старій версії main



![Image](https://github.com/Neoversity/PPF_BP_Personal_assistant/assets/130400459/f473ef9d-10fb-4ece-b112-8d6eb0ba550d)

це було ще вчора.

**Comment by bobantonbob** [comment]
доречи ти кодиш  у старій версії main



![Image](https://github.com/Neoversity/PPF_BP_Personal_assistant/assets/130400459/f473ef9d-10fb-4ece-b112-8d6eb0ba550d)

це було ще вчора.
